# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad8d895fef86affd6b28b463a2bf03dcf505af50e78601503836a5b623d4c231a311cc1cab26bc60a4f64ccf1f75a4fc58ccab6750315459c4daefe4992aac0e

test:
  secret_key_base: a752448cb569e08808309fd99f04d11e7bd6fc369e4bdc0fd943b360c22fa1835e7cce8b6fa1b6af7605d738b8d55282eeae86ecdfb7190c8627015dc4cf0543

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
